version: 2
sources:
  - name: adventure_works
    description: "Base adventure_works"
    tables:
      - name: production_product
      - name: production_productsubcategory
      - name: production_productcategory

      - name: sales_customer
      - name: sales_salesorderdetail
      - name: sales_salesorderheader
      - name: sales_creditcard
      - name: sales_salesorderheadersalesreason
      - name: sales_salesreason
      - name: sales_salesperson
      - name: sales_salesterritory

      - name: person_person
      - name: person_emailaddress
      - name: person_address
      - name: person_stateprovince
      - name: person_countryregion