version: 2

models:
  - name: dim_produto
    description: "Dimensão de produtos, contendo informações descritivas e comerciais dos produtos."
    columns:
      - name: productid
        description: "Identificador único do produto."
        tests:
          - not_null
          - unique

      - name: name
        description: "Nome do produto."

      - name: productnumber
        description: "Código do produto."

      - name: color
        description: "Cor do produto."

      - name: listprice
        description: "Preço de tabela do produto."

      - name: safetystocklevel
        description: "Nível mínimo de estoque de segurança."

      - name: reorderpoint
        description: "Ponto de reposição do estoque."

      - name: standardcost
        description: "Custo padrão do produto."

      - name: size
        description: "Tamanho do produto."

      - name: sizeunitmeasurecode
        description: "Unidade de medida associada ao tamanho."

      - name: weight
        description: "Peso do produto."

      - name: weightunitmeasurecode
        description: "Unidade de medida associada ao peso."

  - name: dim_tempo
    description: "Dimensão de tempo, utilizada para análises temporais de vendas."
    columns:
      - name: orderdate
        description: "Data do pedido."
        tests:
          - not_null
          - unique

      - name: ano
        description: "Ano da data do pedido."

      - name: trimestre
        description: "Trimestre do ano (1 a 4)."

      - name: mes
        description: "Mês do ano (1 a 12)."

      - name: dia
        description: "Dia do mês."

      - name: mes_nome
        description: "Nome do mês."

      - name: dia_da_semana
        description: "Nome do dia da semana."

  - name: dim_territorio
    description: "Dimensão de territórios de vendas, utilizada para análises geográficas."
    columns:
      - name: territoryid
        description: "Identificador único do território."
        tests:
          - not_null
          - unique

      - name: territory_name
        description: "Nome do território."

      - name: countryregioncode
        description: "Código do país ou região."

      - name: territory_group
        description: "Grupo do território."

      - name: modifieddate
        description: "Data da última atualização do registro."

  - name: fct_sales
    description: >
      Tabela fato de vendas no nível de item do pedido (salesorderdetailid).
      Consolida dados de pedidos, produtos, clientes, vendedor, geografia
      e métricas financeiras brutas e líquidas.
      Grão: 1 linha por item de pedido.
    columns:
      - name: salesorderdetailid
        description: "Identificador único da linha do pedido (grão da tabela fato)."
        tests:
          - not_null
          - unique

      - name: salesorderid
        description: "Identificador do pedido de venda."
        tests:
          - not_null

      - name: orderdate
        description: "Data em que o pedido foi realizado."
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_tempo')
                field: orderdate

      - name: customerid
        description: "Identificador do cliente."
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_cliente')
                field: customerid

      - name: status
        description: "Status do pedido de venda."

      - name: territoryid
        description: "Identificador do território de vendas."
        tests:
          - relationships:
              arguments:
                to: ref('dim_territorio')
                field: territoryid

      - name: cardtype
        description: "Tipo do cartão utilizado na compra."

      - name: salesreason_name
        description: "Motivo da venda (ex.: Promotion)."

      - name: productid
        description: "Identificador do produto vendido."
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_produto')
                field: productid

      - name: specialofferid
        description: "Identificador da oferta especial aplicada."

      - name: orderqty
        description: "Quantidade de unidades vendidas."
        tests:
          - not_null

      - name: unitprice
        description: "Preço unitário do produto no momento da venda."
        tests:
          - not_null

      - name: unitpricediscount
        description: "Percentual de desconto aplicado ao produto."
        tests:
          - not_null

      - name: gross_sales
        description: "Valor bruto negociado por item: unitprice * orderqty."
        tests:
          - not_null

      - name: net_sales
        description: "Valor líquido negociado por item: unitprice * orderqty * (1 - unitpricediscount)."
        tests:
          - not_null

      - name: city
        description: "Cidade do endereço de entrega."

      - name: state_name
        description: "Estado ou província do endereço de entrega."

      - name: country_name
        description: "País ou região do endereço de entrega."

      - name: salespersonid
        description: "Identificador do vendedor."

      - name: salesperson_name
        description: "Nome completo do vendedor."
