version: 2

models:
  - name: dim_produto
    description: "Dimensão de produtos, contendo informações descritivas e comerciais dos produtos."
    columns:
      - name: productid
        description: "Identificador único do produto."
        tests:
          - not_null
          - unique

      - name: name
        description: "Nome do produto."

      - name: productnumber
        description: "Código do produto."

      - name: color
        description: "Cor do produto."

      - name: listprice
        description: "Preço de tabela do produto."

      - name: safetystocklevel
        description: "Nível mínimo de estoque de segurança."

      - name: reorderpoint
        description: "Ponto de reposição do estoque."

      - name: standardcost
        description: "Custo padrão do produto."

      - name: size
        description: "Tamanho do produto."

      - name: sizeunitmeasurecode
        description: "Unidade de medida associada ao tamanho."

      - name: weight
        description: "Peso do produto."

      - name: weightunitmeasurecode
        description: "Unidade de medida associada ao peso."

  - name: dim_tempo
    description: "Dimensão de tempo, utilizada para análises temporais de vendas."
    columns:
      - name: orderdate
        description: "Data do pedido."
        tests:
          - not_null
          - unique

      - name: ano
        description: "Ano da data do pedido."

      - name: trimestre
        description: "Trimestre do ano (1 a 4)."

      - name: mes
        description: "Mês do ano (1 a 12)."

      - name: dia
        description: "Dia do mês."

      - name: mes_nome
        description: "Nome do mês."

      - name: dia_da_semana
        description: "Nome do dia da semana."

  - name: dim_territorio
    description: "Dimensão de territórios de vendas, utilizada para análises geográficas."
    columns:
      - name: territoryid
        description: "Identificador único do território."
        tests:
          - not_null
          - unique

      - name: territory_name
        description: "Nome do território."

      - name: countryregioncode
        description: "Código do país ou região."

      - name: territory_group
        description: "Grupo do território."

      - name: modifieddate
        description: "Data da última atualização do registro."

  