version: 2

models:

  - name: dim_tempo
    description: "Dimensão de tempo, utilizada para análises temporais de vendas."
    columns:
      - name: orderdate
        description: "Data do pedido."
        tests:
          - not_null
          - unique

      - name: ano
        description: "Ano da data do pedido."

      - name: trimestre
        description: "Trimestre do ano (1 a 4)."

      - name: mes
        description: "Mês do ano (1 a 12)."

      - name: dia
        description: "Dia do mês."

      - name: mes_nome
        description: "Nome do mês."

      - name: dia_da_semana
        description: "Nome do dia da semana."

  - name: dim_territorio
    description: "Dimensão de territórios de vendas, utilizada para análises geográficas."
    columns:
      - name: territoryid
        description: "Identificador único do território."
        tests:
          - not_null
          - unique

      - name: territory_name
        description: "Nome do território."

      - name: countryregioncode
        description: "Código do país ou região."

      - name: territory_group
        description: "Grupo do território."

      - name: modifieddate
        description: "Data da última atualização do registro."

  